/*-
 * =====LICENSE-START=====
 * Java 11 Application
 * ------
 * Copyright (C) 2020 - 2023 Organization Name
 * ------
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * =====LICENSE-END=====
 */

// Generated by Akka gRPC. DO NOT EDIT.
package io.eigr.astreu.manager;

import akka.actor.*;
import akka.grpc.*;
import akka.grpc.internal.*;
import akka.grpc.javadsl.*;
import akka.stream.*;

import com.google.protobuf.*;
import io.grpc.*;

import scala.concurrent.*;

import static io.eigr.astreu.manager.TopicService.Serializers.*;


public abstract class TopicServiceClient extends TopicServiceClientPowerApi implements TopicService, AkkaGrpcClient {
  public static final TopicServiceClient create(GrpcClientSettings settings, ClassicActorSystemProvider sys) {
    return new DefaultTopicServiceClient(settings, sys);
  }

  protected final static class DefaultTopicServiceClient extends TopicServiceClient {

      private final ClientState clientState;
      private final GrpcClientSettings settings;
      private final io.grpc.CallOptions options;
      private final Materializer mat;
      private final ExecutionContext ec;

      private DefaultTopicServiceClient(GrpcClientSettings settings, ClassicActorSystemProvider sys) {
        this.settings = settings;
        this.mat = SystemMaterializer.get(sys).materializer();
        this.ec = sys.classicSystem().dispatcher();
        this.clientState = new ClientState(
          settings,
          akka.event.Logging$.MODULE$.apply(sys.classicSystem(), DefaultTopicServiceClient.class, akka.event.LogSource$.MODULE$.<DefaultTopicServiceClient>fromAnyClass()),
          sys);
        this.options = NettyClientUtils.callOptions(settings);

        sys.classicSystem().getWhenTerminated().whenComplete((v, e) -> close());
      }

  
    
      private final SingleResponseRequestBuilder<Topic, TopicInfo> infoRequestBuilder(akka.grpc.internal.InternalChannel channel){
        return new JavaUnaryRequestBuilder<>(infoDescriptor, channel, options, settings, ec);
      }
    
  
    
      private final SingleResponseRequestBuilder<Topic, Empty> dropRequestBuilder(akka.grpc.internal.InternalChannel channel){
        return new JavaUnaryRequestBuilder<>(dropDescriptor, channel, options, settings, ec);
      }
    
  
    
      private final SingleResponseRequestBuilder<Topic, TopicInfo> createRequestBuilder(akka.grpc.internal.InternalChannel channel){
        return new JavaUnaryRequestBuilder<>(createDescriptor, channel, options, settings, ec);
      }
    
  

      

        /**
         * For access to method metadata use the parameterless version of info
         */
        public java.util.concurrent.CompletionStage<TopicInfo> info(Topic request) {
          return info().invoke(request);
        }

        /**
         * Lower level "lifted" version of the method, giving access to request metadata etc.
         * prefer info(io.eigr.astreu.manager.Topic) if possible.
         */
        
          public SingleResponseRequestBuilder<Topic, TopicInfo> info()
        
        {
          return infoRequestBuilder(clientState.internalChannel());
        }
      

        /**
         * For access to method metadata use the parameterless version of drop
         */
        public java.util.concurrent.CompletionStage<Empty> drop(Topic request) {
          return drop().invoke(request);
        }

        /**
         * Lower level "lifted" version of the method, giving access to request metadata etc.
         * prefer drop(io.eigr.astreu.manager.Topic) if possible.
         */
        
          public SingleResponseRequestBuilder<Topic, Empty> drop()
        
        {
          return dropRequestBuilder(clientState.internalChannel());
        }
      

        /**
         * For access to method metadata use the parameterless version of create
         */
        public java.util.concurrent.CompletionStage<TopicInfo> create(Topic request) {
          return create().invoke(request);
        }

        /**
         * Lower level "lifted" version of the method, giving access to request metadata etc.
         * prefer create(io.eigr.astreu.manager.Topic) if possible.
         */
        
          public SingleResponseRequestBuilder<Topic, TopicInfo> create()
        
        {
          return createRequestBuilder(clientState.internalChannel());
        }
      

      
        private static MethodDescriptor<Topic, TopicInfo> infoDescriptor =
          MethodDescriptor.<Topic, TopicInfo>newBuilder()
            .setType(
   MethodDescriptor.MethodType.UNARY 
  
  
  
)
            .setFullMethodName(MethodDescriptor.generateFullMethodName("astreu.core.protocol.manager.TopicService", "Info"))
            .setRequestMarshaller(new ProtoMarshaller<Topic>(TopicSerializer))
            .setResponseMarshaller(new ProtoMarshaller<TopicInfo>(TopicInfoSerializer))
            .setSampledToLocalTracing(true)
            .build();
        
        private static MethodDescriptor<Topic, Empty> dropDescriptor =
          MethodDescriptor.<Topic, Empty>newBuilder()
            .setType(
   MethodDescriptor.MethodType.UNARY 
  
  
  
)
            .setFullMethodName(MethodDescriptor.generateFullMethodName("astreu.core.protocol.manager.TopicService", "Drop"))
            .setRequestMarshaller(new ProtoMarshaller<Topic>(TopicSerializer))
            .setResponseMarshaller(new ProtoMarshaller<Empty>(EmptySerializer))
            .setSampledToLocalTracing(true)
            .build();
        
        private static MethodDescriptor<Topic, TopicInfo> createDescriptor =
          MethodDescriptor.<Topic, TopicInfo>newBuilder()
            .setType(
   MethodDescriptor.MethodType.UNARY 
  
  
  
)
            .setFullMethodName(MethodDescriptor.generateFullMethodName("astreu.core.protocol.manager.TopicService", "Create"))
            .setRequestMarshaller(new ProtoMarshaller<Topic>(TopicSerializer))
            .setResponseMarshaller(new ProtoMarshaller<TopicInfo>(TopicInfoSerializer))
            .setSampledToLocalTracing(true)
            .build();
        

      /**
       * Initiates a shutdown in which preexisting and new calls are cancelled.
       */
      public java.util.concurrent.CompletionStage<akka.Done> close() {
        return clientState.closeCS() ;
      }

     /**
      * Returns a CompletionState that completes successfully when shutdown via close()
      * or exceptionally if a connection can not be established after maxConnectionAttempts.
      */
      public java.util.concurrent.CompletionStage<akka.Done> closed() {
        return clientState.closedCS();
      }
  }

}



