/*-
 * =====LICENSE-START=====
 * Java 11 Application
 * ------
 * Copyright (C) 2020 - 2023 Organization Name
 * ------
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * =====LICENSE-END=====
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: astreu/core/protocol/protocol.proto

package io.eigr.astreu.protocol;

public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:astreu.core.protocol.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier of a ack message
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  String getUuid();
  /**
   * <pre>
   * Unique identifier of a ack message
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   * Reason of the message confirmation
   * </pre>
   *
   * <code>.astreu.core.protocol.Ack.Reason reason = 2;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <pre>
   * Reason of the message confirmation
   * </pre>
   *
   * <code>.astreu.core.protocol.Ack.Reason reason = 2;</code>
   * @return The reason.
   */
  Ack.Reason getReason();

  /**
   * <pre>
   * Metadata. Must contain the original message uuid in the 'correlation' attribute
   * </pre>
   *
   * <code>.astreu.core.protocol.Metadata metadata = 3;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Metadata. Must contain the original message uuid in the 'correlation' attribute
   * </pre>
   *
   * <code>.astreu.core.protocol.Metadata metadata = 3;</code>
   * @return The metadata.
   */
  Metadata getMetadata();
  /**
   * <pre>
   * Metadata. Must contain the original message uuid in the 'correlation' attribute
   * </pre>
   *
   * <code>.astreu.core.protocol.Metadata metadata = 3;</code>
   */
  MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * Subscription identifier
   * </pre>
   *
   * <code>string subscription = 4;</code>
   * @return The subscription.
   */
  String getSubscription();
  /**
   * <pre>
   * Subscription identifier
   * </pre>
   *
   * <code>string subscription = 4;</code>
   * @return The bytes for subscription.
   */
  com.google.protobuf.ByteString
      getSubscriptionBytes();
}
