/*-
 * =====LICENSE-START=====
 * Java 11 Application
 * ------
 * Copyright (C) 2020 - 2023 Organization Name
 * ------
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * =====LICENSE-END=====
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: astreu/core/protocol/protocol.proto

package io.eigr.astreu.protocol;


import com.google.protobuf.*;


public interface ConnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:astreu.core.protocol.Connect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  String getUuid();
  /**
   * <pre>
   * Unique identifier
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   * name of a topic to register.
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  String getTopic();
  /**
   * <pre>
   * name of a topic to register.
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <pre>
   * can be created in advance or dynamically (if the topic does not exist at the time of connection it will be created)
   * </pre>
   *
   * <code>string subscription = 3;</code>
   * @return The subscription.
   */
  String getSubscription();
  /**
   * <pre>
   * can be created in advance or dynamically (if the topic does not exist at the time of connection it will be created)
   * </pre>
   *
   * <code>string subscription = 3;</code>
   * @return The bytes for subscription.
   */
  com.google.protobuf.ByteString
      getSubscriptionBytes();

  /**
   * <pre>
   * A property map can be passed to the Broker in order to make some type of configuration
   * </pre>
   *
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */
  int getPropertiesCount();
  /**
   * <pre>
   * A property map can be passed to the Broker in order to make some type of configuration
   * </pre>
   *
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */
  boolean containsProperties(
      String key);
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getProperties();
  /**
   * <pre>
   * A property map can be passed to the Broker in order to make some type of configuration
   * </pre>
   *
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */
  java.util.Map<String, String>
  getPropertiesMap();
  /**
   * <pre>
   * A property map can be passed to the Broker in order to make some type of configuration
   * </pre>
   *
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */

  String getPropertiesOrDefault(
      String key,
      String defaultValue);
  /**
   * <pre>
   * A property map can be passed to the Broker in order to make some type of configuration
   * </pre>
   *
   * <code>map&lt;string, string&gt; properties = 4;</code>
   */

  String getPropertiesOrThrow(
      String key);

  /**
   * <pre>
   * Moment of message creation
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * Moment of message creation
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   * @return The timestamp.
   */
  Timestamp getTimestamp();
  /**
   * <pre>
   * Moment of message creation
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   */
  TimestampOrBuilder getTimestampOrBuilder();
}
