/*-
 * =====LICENSE-START=====
 * Java 11 Application
 * ------
 * Copyright (C) 2020 - 2023 Organization Name
 * ------
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * =====LICENSE-END=====
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: astreu/core/protocol/protocol.proto

package io.eigr.astreu.protocol;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:astreu.core.protocol.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.astreu.core.protocol.System system = 1;</code>
   * @return Whether the system field is set.
   */
  boolean hasSystem();
  /**
   * <code>.astreu.core.protocol.System system = 1;</code>
   * @return The system.
   */
  System getSystem();
  /**
   * <code>.astreu.core.protocol.System system = 1;</code>
   */
  SystemOrBuilder getSystemOrBuilder();

  /**
   * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
   * @return Whether the exchange field is set.
   */
  boolean hasExchange();
  /**
   * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
   * @return The exchange.
   */
  Exchange getExchange();
  /**
   * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
   */
  ExchangeOrBuilder getExchangeOrBuilder();

  /**
   * <code>.astreu.core.protocol.Ack ack = 3;</code>
   * @return Whether the ack field is set.
   */
  boolean hasAck();
  /**
   * <code>.astreu.core.protocol.Ack ack = 3;</code>
   * @return The ack.
   */
  Ack getAck();
  /**
   * <code>.astreu.core.protocol.Ack ack = 3;</code>
   */
  AckOrBuilder getAckOrBuilder();

  public Message.DataCase getDataCase();
}
