/*-
 * =====LICENSE-START=====
 * Java 11 Application
 * ------
 * Copyright (C) 2020 - 2023 Organization Name
 * ------
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * =====LICENSE-END=====
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: astreu/core/protocol/protocol.proto

package io.eigr.astreu.protocol;

/**
 * <pre>
 * Message is a box for various sub types of messages
 * that can be exchanged between the clients and the Broker via gRPC stream channel.
 * It can currently contain one of three message types:
 *     System: System messages, such as Connect and Disconnect, among others (see System).
 *     Exchange: The useful message between producers and consumers (see Exchange)
 *     Ack: A receipt confirmation message (see Ack)
 * </pre>
 *
 * Protobuf type {@code astreu.core.protocol.Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:astreu.core.protocol.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            System.Builder subBuilder = null;
            if (dataCase_ == 1) {
              subBuilder = ((System) data_).toBuilder();
            }
            data_ =
                input.readMessage(System.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((System) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 1;
            break;
          }
          case 18: {
            Exchange.Builder subBuilder = null;
            if (dataCase_ == 2) {
              subBuilder = ((Exchange) data_).toBuilder();
            }
            data_ =
                input.readMessage(Exchange.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Exchange) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 2;
            break;
          }
          case 26: {
            Ack.Builder subBuilder = null;
            if (dataCase_ == 3) {
              subBuilder = ((Ack) data_).toBuilder();
            }
            data_ =
                input.readMessage(Ack.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Ack) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProtocolProto.internal_static_astreu_core_protocol_Message_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProtocolProto.internal_static_astreu_core_protocol_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Message.class, Builder.class);
  }

  private int dataCase_ = 0;
  private Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SYSTEM(1),
    EXCHANGE(2),
    ACK(3),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 1: return SYSTEM;
        case 2: return EXCHANGE;
        case 3: return ACK;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int SYSTEM_FIELD_NUMBER = 1;
  /**
   * <code>.astreu.core.protocol.System system = 1;</code>
   * @return Whether the system field is set.
   */
  public boolean hasSystem() {
    return dataCase_ == 1;
  }
  /**
   * <code>.astreu.core.protocol.System system = 1;</code>
   * @return The system.
   */
  public System getSystem() {
    if (dataCase_ == 1) {
       return (System) data_;
    }
    return System.getDefaultInstance();
  }
  /**
   * <code>.astreu.core.protocol.System system = 1;</code>
   */
  public SystemOrBuilder getSystemOrBuilder() {
    if (dataCase_ == 1) {
       return (System) data_;
    }
    return System.getDefaultInstance();
  }

  public static final int EXCHANGE_FIELD_NUMBER = 2;
  /**
   * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
   * @return Whether the exchange field is set.
   */
  public boolean hasExchange() {
    return dataCase_ == 2;
  }
  /**
   * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
   * @return The exchange.
   */
  public Exchange getExchange() {
    if (dataCase_ == 2) {
       return (Exchange) data_;
    }
    return Exchange.getDefaultInstance();
  }
  /**
   * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
   */
  public ExchangeOrBuilder getExchangeOrBuilder() {
    if (dataCase_ == 2) {
       return (Exchange) data_;
    }
    return Exchange.getDefaultInstance();
  }

  public static final int ACK_FIELD_NUMBER = 3;
  /**
   * <code>.astreu.core.protocol.Ack ack = 3;</code>
   * @return Whether the ack field is set.
   */
  public boolean hasAck() {
    return dataCase_ == 3;
  }
  /**
   * <code>.astreu.core.protocol.Ack ack = 3;</code>
   * @return The ack.
   */
  public Ack getAck() {
    if (dataCase_ == 3) {
       return (Ack) data_;
    }
    return Ack.getDefaultInstance();
  }
  /**
   * <code>.astreu.core.protocol.Ack ack = 3;</code>
   */
  public AckOrBuilder getAckOrBuilder() {
    if (dataCase_ == 3) {
       return (Ack) data_;
    }
    return Ack.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataCase_ == 1) {
      output.writeMessage(1, (System) data_);
    }
    if (dataCase_ == 2) {
      output.writeMessage(2, (Exchange) data_);
    }
    if (dataCase_ == 3) {
      output.writeMessage(3, (Ack) data_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (System) data_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (Exchange) data_);
    }
    if (dataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (Ack) data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Message)) {
      return super.equals(obj);
    }
    Message other = (Message) obj;

    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 1:
        if (!getSystem()
            .equals(other.getSystem())) return false;
        break;
      case 2:
        if (!getExchange()
            .equals(other.getExchange())) return false;
        break;
      case 3:
        if (!getAck()
            .equals(other.getAck())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (dataCase_) {
      case 1:
        hash = (37 * hash) + SYSTEM_FIELD_NUMBER;
        hash = (53 * hash) + getSystem().hashCode();
        break;
      case 2:
        hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
        hash = (53 * hash) + getExchange().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ACK_FIELD_NUMBER;
        hash = (53 * hash) + getAck().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message is a box for various sub types of messages
   * that can be exchanged between the clients and the Broker via gRPC stream channel.
   * It can currently contain one of three message types:
   *     System: System messages, such as Connect and Disconnect, among others (see System).
   *     Exchange: The useful message between producers and consumers (see Exchange)
   *     Ack: A receipt confirmation message (see Ack)
   * </pre>
   *
   * Protobuf type {@code astreu.core.protocol.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:astreu.core.protocol.Message)
      MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolProto.internal_static_astreu_core_protocol_Message_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolProto.internal_static_astreu_core_protocol_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    // Construct using io.eigr.astreu.protocol.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProtocolProto.internal_static_astreu_core_protocol_Message_descriptor;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return Message.getDefaultInstance();
    }

    @Override
    public Message build() {
      Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Message buildPartial() {
      Message result = new Message(this);
      if (dataCase_ == 1) {
        if (systemBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = systemBuilder_.build();
        }
      }
      if (dataCase_ == 2) {
        if (exchangeBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = exchangeBuilder_.build();
        }
      }
      if (dataCase_ == 3) {
        if (ackBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = ackBuilder_.build();
        }
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Message) {
        return mergeFrom((Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Message other) {
      if (other == Message.getDefaultInstance()) return this;
      switch (other.getDataCase()) {
        case SYSTEM: {
          mergeSystem(other.getSystem());
          break;
        }
        case EXCHANGE: {
          mergeExchange(other.getExchange());
          break;
        }
        case ACK: {
          mergeAck(other.getAck());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        System, System.Builder, SystemOrBuilder> systemBuilder_;
    /**
     * <code>.astreu.core.protocol.System system = 1;</code>
     * @return Whether the system field is set.
     */
    public boolean hasSystem() {
      return dataCase_ == 1;
    }
    /**
     * <code>.astreu.core.protocol.System system = 1;</code>
     * @return The system.
     */
    public System getSystem() {
      if (systemBuilder_ == null) {
        if (dataCase_ == 1) {
          return (System) data_;
        }
        return System.getDefaultInstance();
      } else {
        if (dataCase_ == 1) {
          return systemBuilder_.getMessage();
        }
        return System.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.System system = 1;</code>
     */
    public Builder setSystem(System value) {
      if (systemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        systemBuilder_.setMessage(value);
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.System system = 1;</code>
     */
    public Builder setSystem(
        System.Builder builderForValue) {
      if (systemBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        systemBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.System system = 1;</code>
     */
    public Builder mergeSystem(System value) {
      if (systemBuilder_ == null) {
        if (dataCase_ == 1 &&
            data_ != System.getDefaultInstance()) {
          data_ = System.newBuilder((System) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 1) {
          systemBuilder_.mergeFrom(value);
        }
        systemBuilder_.setMessage(value);
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.System system = 1;</code>
     */
    public Builder clearSystem() {
      if (systemBuilder_ == null) {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
        }
        systemBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.astreu.core.protocol.System system = 1;</code>
     */
    public System.Builder getSystemBuilder() {
      return getSystemFieldBuilder().getBuilder();
    }
    /**
     * <code>.astreu.core.protocol.System system = 1;</code>
     */
    public SystemOrBuilder getSystemOrBuilder() {
      if ((dataCase_ == 1) && (systemBuilder_ != null)) {
        return systemBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 1) {
          return (System) data_;
        }
        return System.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.System system = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        System, System.Builder, SystemOrBuilder>
        getSystemFieldBuilder() {
      if (systemBuilder_ == null) {
        if (!(dataCase_ == 1)) {
          data_ = System.getDefaultInstance();
        }
        systemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            System, System.Builder, SystemOrBuilder>(
                (System) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 1;
      onChanged();;
      return systemBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        Exchange, Exchange.Builder, ExchangeOrBuilder> exchangeBuilder_;
    /**
     * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
     * @return Whether the exchange field is set.
     */
    public boolean hasExchange() {
      return dataCase_ == 2;
    }
    /**
     * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
     * @return The exchange.
     */
    public Exchange getExchange() {
      if (exchangeBuilder_ == null) {
        if (dataCase_ == 2) {
          return (Exchange) data_;
        }
        return Exchange.getDefaultInstance();
      } else {
        if (dataCase_ == 2) {
          return exchangeBuilder_.getMessage();
        }
        return Exchange.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
     */
    public Builder setExchange(Exchange value) {
      if (exchangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        exchangeBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
     */
    public Builder setExchange(
        Exchange.Builder builderForValue) {
      if (exchangeBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        exchangeBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
     */
    public Builder mergeExchange(Exchange value) {
      if (exchangeBuilder_ == null) {
        if (dataCase_ == 2 &&
            data_ != Exchange.getDefaultInstance()) {
          data_ = Exchange.newBuilder((Exchange) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 2) {
          exchangeBuilder_.mergeFrom(value);
        }
        exchangeBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
     */
    public Builder clearExchange() {
      if (exchangeBuilder_ == null) {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
        }
        exchangeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
     */
    public Exchange.Builder getExchangeBuilder() {
      return getExchangeFieldBuilder().getBuilder();
    }
    /**
     * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
     */
    public ExchangeOrBuilder getExchangeOrBuilder() {
      if ((dataCase_ == 2) && (exchangeBuilder_ != null)) {
        return exchangeBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 2) {
          return (Exchange) data_;
        }
        return Exchange.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Exchange exchange = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Exchange, Exchange.Builder, ExchangeOrBuilder>
        getExchangeFieldBuilder() {
      if (exchangeBuilder_ == null) {
        if (!(dataCase_ == 2)) {
          data_ = Exchange.getDefaultInstance();
        }
        exchangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Exchange, Exchange.Builder, ExchangeOrBuilder>(
                (Exchange) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 2;
      onChanged();;
      return exchangeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        Ack, Ack.Builder, AckOrBuilder> ackBuilder_;
    /**
     * <code>.astreu.core.protocol.Ack ack = 3;</code>
     * @return Whether the ack field is set.
     */
    public boolean hasAck() {
      return dataCase_ == 3;
    }
    /**
     * <code>.astreu.core.protocol.Ack ack = 3;</code>
     * @return The ack.
     */
    public Ack getAck() {
      if (ackBuilder_ == null) {
        if (dataCase_ == 3) {
          return (Ack) data_;
        }
        return Ack.getDefaultInstance();
      } else {
        if (dataCase_ == 3) {
          return ackBuilder_.getMessage();
        }
        return Ack.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Ack ack = 3;</code>
     */
    public Builder setAck(Ack value) {
      if (ackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        ackBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Ack ack = 3;</code>
     */
    public Builder setAck(
        Ack.Builder builderForValue) {
      if (ackBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        ackBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Ack ack = 3;</code>
     */
    public Builder mergeAck(Ack value) {
      if (ackBuilder_ == null) {
        if (dataCase_ == 3 &&
            data_ != Ack.getDefaultInstance()) {
          data_ = Ack.newBuilder((Ack) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 3) {
          ackBuilder_.mergeFrom(value);
        }
        ackBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Ack ack = 3;</code>
     */
    public Builder clearAck() {
      if (ackBuilder_ == null) {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
        }
        ackBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Ack ack = 3;</code>
     */
    public Ack.Builder getAckBuilder() {
      return getAckFieldBuilder().getBuilder();
    }
    /**
     * <code>.astreu.core.protocol.Ack ack = 3;</code>
     */
    public AckOrBuilder getAckOrBuilder() {
      if ((dataCase_ == 3) && (ackBuilder_ != null)) {
        return ackBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 3) {
          return (Ack) data_;
        }
        return Ack.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Ack ack = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Ack, Ack.Builder, AckOrBuilder>
        getAckFieldBuilder() {
      if (ackBuilder_ == null) {
        if (!(dataCase_ == 3)) {
          data_ = Ack.getDefaultInstance();
        }
        ackBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Ack, Ack.Builder, AckOrBuilder>(
                (Ack) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 3;
      onChanged();;
      return ackBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:astreu.core.protocol.Message)
  }

  // @@protoc_insertion_point(class_scope:astreu.core.protocol.Message)
  private static final Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Message();
  }

  public static Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @Override
  public Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

