/*-
 * =====LICENSE-START=====
 * Java 11 Application
 * ------
 * Copyright (C) 2020 - 2023 Organization Name
 * ------
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * =====LICENSE-END=====
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: astreu/core/protocol/protocol.proto

package io.eigr.astreu.protocol;

public interface SystemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:astreu.core.protocol.System)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.astreu.core.protocol.Info info = 1;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.astreu.core.protocol.Info info = 1;</code>
   * @return The info.
   */
  Info getInfo();
  /**
   * <code>.astreu.core.protocol.Info info = 1;</code>
   */
  InfoOrBuilder getInfoOrBuilder();

  /**
   * <code>.astreu.core.protocol.Failure failure = 2;</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <code>.astreu.core.protocol.Failure failure = 2;</code>
   * @return The failure.
   */
  Failure getFailure();
  /**
   * <code>.astreu.core.protocol.Failure failure = 2;</code>
   */
  FailureOrBuilder getFailureOrBuilder();

  /**
   * <code>.astreu.core.protocol.Connect connect = 3;</code>
   * @return Whether the connect field is set.
   */
  boolean hasConnect();
  /**
   * <code>.astreu.core.protocol.Connect connect = 3;</code>
   * @return The connect.
   */
  Connect getConnect();
  /**
   * <code>.astreu.core.protocol.Connect connect = 3;</code>
   */
  ConnectOrBuilder getConnectOrBuilder();

  /**
   * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
   * @return Whether the disconnect field is set.
   */
  boolean hasDisconnect();
  /**
   * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
   * @return The disconnect.
   */
  Disconnect getDisconnect();
  /**
   * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
   */
  DisconnectOrBuilder getDisconnectOrBuilder();

  public System.DataCase getDataCase();
}
