/*-
 * =====LICENSE-START=====
 * Java 11 Application
 * ------
 * Copyright (C) 2020 - 2023 Organization Name
 * ------
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * =====LICENSE-END=====
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: astreu/core/protocol/protocol.proto

package io.eigr.astreu.protocol;

/**
 * <pre>
 * A system message can be sent with one of the following constituents:
 *     Info: see Info
 *     Failure: see Failure
 *     Connect: see Connect
 *     Disconnect: see Disconnect
 * </pre>
 *
 * Protobuf type {@code astreu.core.protocol.System}
 */
public  final class System extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:astreu.core.protocol.System)
    SystemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use System.newBuilder() to construct.
  private System(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private System() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new System();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private System(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            Info.Builder subBuilder = null;
            if (dataCase_ == 1) {
              subBuilder = ((Info) data_).toBuilder();
            }
            data_ =
                input.readMessage(Info.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Info) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 1;
            break;
          }
          case 18: {
            Failure.Builder subBuilder = null;
            if (dataCase_ == 2) {
              subBuilder = ((Failure) data_).toBuilder();
            }
            data_ =
                input.readMessage(Failure.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Failure) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 2;
            break;
          }
          case 26: {
            Connect.Builder subBuilder = null;
            if (dataCase_ == 3) {
              subBuilder = ((Connect) data_).toBuilder();
            }
            data_ =
                input.readMessage(Connect.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Connect) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 3;
            break;
          }
          case 34: {
            Disconnect.Builder subBuilder = null;
            if (dataCase_ == 4) {
              subBuilder = ((Disconnect) data_).toBuilder();
            }
            data_ =
                input.readMessage(Disconnect.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Disconnect) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProtocolProto.internal_static_astreu_core_protocol_System_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProtocolProto.internal_static_astreu_core_protocol_System_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            System.class, Builder.class);
  }

  private int dataCase_ = 0;
  private Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INFO(1),
    FAILURE(2),
    CONNECT(3),
    DISCONNECT(4),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 1: return INFO;
        case 2: return FAILURE;
        case 3: return CONNECT;
        case 4: return DISCONNECT;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int INFO_FIELD_NUMBER = 1;
  /**
   * <code>.astreu.core.protocol.Info info = 1;</code>
   * @return Whether the info field is set.
   */
  public boolean hasInfo() {
    return dataCase_ == 1;
  }
  /**
   * <code>.astreu.core.protocol.Info info = 1;</code>
   * @return The info.
   */
  public Info getInfo() {
    if (dataCase_ == 1) {
       return (Info) data_;
    }
    return Info.getDefaultInstance();
  }
  /**
   * <code>.astreu.core.protocol.Info info = 1;</code>
   */
  public InfoOrBuilder getInfoOrBuilder() {
    if (dataCase_ == 1) {
       return (Info) data_;
    }
    return Info.getDefaultInstance();
  }

  public static final int FAILURE_FIELD_NUMBER = 2;
  /**
   * <code>.astreu.core.protocol.Failure failure = 2;</code>
   * @return Whether the failure field is set.
   */
  public boolean hasFailure() {
    return dataCase_ == 2;
  }
  /**
   * <code>.astreu.core.protocol.Failure failure = 2;</code>
   * @return The failure.
   */
  public Failure getFailure() {
    if (dataCase_ == 2) {
       return (Failure) data_;
    }
    return Failure.getDefaultInstance();
  }
  /**
   * <code>.astreu.core.protocol.Failure failure = 2;</code>
   */
  public FailureOrBuilder getFailureOrBuilder() {
    if (dataCase_ == 2) {
       return (Failure) data_;
    }
    return Failure.getDefaultInstance();
  }

  public static final int CONNECT_FIELD_NUMBER = 3;
  /**
   * <code>.astreu.core.protocol.Connect connect = 3;</code>
   * @return Whether the connect field is set.
   */
  public boolean hasConnect() {
    return dataCase_ == 3;
  }
  /**
   * <code>.astreu.core.protocol.Connect connect = 3;</code>
   * @return The connect.
   */
  public Connect getConnect() {
    if (dataCase_ == 3) {
       return (Connect) data_;
    }
    return Connect.getDefaultInstance();
  }
  /**
   * <code>.astreu.core.protocol.Connect connect = 3;</code>
   */
  public ConnectOrBuilder getConnectOrBuilder() {
    if (dataCase_ == 3) {
       return (Connect) data_;
    }
    return Connect.getDefaultInstance();
  }

  public static final int DISCONNECT_FIELD_NUMBER = 4;
  /**
   * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
   * @return Whether the disconnect field is set.
   */
  public boolean hasDisconnect() {
    return dataCase_ == 4;
  }
  /**
   * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
   * @return The disconnect.
   */
  public Disconnect getDisconnect() {
    if (dataCase_ == 4) {
       return (Disconnect) data_;
    }
    return Disconnect.getDefaultInstance();
  }
  /**
   * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
   */
  public DisconnectOrBuilder getDisconnectOrBuilder() {
    if (dataCase_ == 4) {
       return (Disconnect) data_;
    }
    return Disconnect.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataCase_ == 1) {
      output.writeMessage(1, (Info) data_);
    }
    if (dataCase_ == 2) {
      output.writeMessage(2, (Failure) data_);
    }
    if (dataCase_ == 3) {
      output.writeMessage(3, (Connect) data_);
    }
    if (dataCase_ == 4) {
      output.writeMessage(4, (Disconnect) data_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (Info) data_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (Failure) data_);
    }
    if (dataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (Connect) data_);
    }
    if (dataCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (Disconnect) data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof System)) {
      return super.equals(obj);
    }
    System other = (System) obj;

    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 1:
        if (!getInfo()
            .equals(other.getInfo())) return false;
        break;
      case 2:
        if (!getFailure()
            .equals(other.getFailure())) return false;
        break;
      case 3:
        if (!getConnect()
            .equals(other.getConnect())) return false;
        break;
      case 4:
        if (!getDisconnect()
            .equals(other.getDisconnect())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (dataCase_) {
      case 1:
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfo().hashCode();
        break;
      case 2:
        hash = (37 * hash) + FAILURE_FIELD_NUMBER;
        hash = (53 * hash) + getFailure().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CONNECT_FIELD_NUMBER;
        hash = (53 * hash) + getConnect().hashCode();
        break;
      case 4:
        hash = (37 * hash) + DISCONNECT_FIELD_NUMBER;
        hash = (53 * hash) + getDisconnect().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static System parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static System parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static System parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static System parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static System parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static System parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static System parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static System parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static System parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static System parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static System parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static System parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(System prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A system message can be sent with one of the following constituents:
   *     Info: see Info
   *     Failure: see Failure
   *     Connect: see Connect
   *     Disconnect: see Disconnect
   * </pre>
   *
   * Protobuf type {@code astreu.core.protocol.System}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:astreu.core.protocol.System)
      SystemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolProto.internal_static_astreu_core_protocol_System_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolProto.internal_static_astreu_core_protocol_System_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              System.class, Builder.class);
    }

    // Construct using io.eigr.astreu.protocol.System.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProtocolProto.internal_static_astreu_core_protocol_System_descriptor;
    }

    @Override
    public System getDefaultInstanceForType() {
      return System.getDefaultInstance();
    }

    @Override
    public System build() {
      System result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public System buildPartial() {
      System result = new System(this);
      if (dataCase_ == 1) {
        if (infoBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = infoBuilder_.build();
        }
      }
      if (dataCase_ == 2) {
        if (failureBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = failureBuilder_.build();
        }
      }
      if (dataCase_ == 3) {
        if (connectBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = connectBuilder_.build();
        }
      }
      if (dataCase_ == 4) {
        if (disconnectBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = disconnectBuilder_.build();
        }
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof System) {
        return mergeFrom((System)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(System other) {
      if (other == System.getDefaultInstance()) return this;
      switch (other.getDataCase()) {
        case INFO: {
          mergeInfo(other.getInfo());
          break;
        }
        case FAILURE: {
          mergeFailure(other.getFailure());
          break;
        }
        case CONNECT: {
          mergeConnect(other.getConnect());
          break;
        }
        case DISCONNECT: {
          mergeDisconnect(other.getDisconnect());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      System parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (System) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        Info, Info.Builder, InfoOrBuilder> infoBuilder_;
    /**
     * <code>.astreu.core.protocol.Info info = 1;</code>
     * @return Whether the info field is set.
     */
    public boolean hasInfo() {
      return dataCase_ == 1;
    }
    /**
     * <code>.astreu.core.protocol.Info info = 1;</code>
     * @return The info.
     */
    public Info getInfo() {
      if (infoBuilder_ == null) {
        if (dataCase_ == 1) {
          return (Info) data_;
        }
        return Info.getDefaultInstance();
      } else {
        if (dataCase_ == 1) {
          return infoBuilder_.getMessage();
        }
        return Info.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Info info = 1;</code>
     */
    public Builder setInfo(Info value) {
      if (infoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        infoBuilder_.setMessage(value);
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Info info = 1;</code>
     */
    public Builder setInfo(
        Info.Builder builderForValue) {
      if (infoBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        infoBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Info info = 1;</code>
     */
    public Builder mergeInfo(Info value) {
      if (infoBuilder_ == null) {
        if (dataCase_ == 1 &&
            data_ != Info.getDefaultInstance()) {
          data_ = Info.newBuilder((Info) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 1) {
          infoBuilder_.mergeFrom(value);
        }
        infoBuilder_.setMessage(value);
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Info info = 1;</code>
     */
    public Builder clearInfo() {
      if (infoBuilder_ == null) {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
        }
        infoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Info info = 1;</code>
     */
    public Info.Builder getInfoBuilder() {
      return getInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.astreu.core.protocol.Info info = 1;</code>
     */
    public InfoOrBuilder getInfoOrBuilder() {
      if ((dataCase_ == 1) && (infoBuilder_ != null)) {
        return infoBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 1) {
          return (Info) data_;
        }
        return Info.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Info info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Info, Info.Builder, InfoOrBuilder>
        getInfoFieldBuilder() {
      if (infoBuilder_ == null) {
        if (!(dataCase_ == 1)) {
          data_ = Info.getDefaultInstance();
        }
        infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Info, Info.Builder, InfoOrBuilder>(
                (Info) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 1;
      onChanged();;
      return infoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        Failure, Failure.Builder, FailureOrBuilder> failureBuilder_;
    /**
     * <code>.astreu.core.protocol.Failure failure = 2;</code>
     * @return Whether the failure field is set.
     */
    public boolean hasFailure() {
      return dataCase_ == 2;
    }
    /**
     * <code>.astreu.core.protocol.Failure failure = 2;</code>
     * @return The failure.
     */
    public Failure getFailure() {
      if (failureBuilder_ == null) {
        if (dataCase_ == 2) {
          return (Failure) data_;
        }
        return Failure.getDefaultInstance();
      } else {
        if (dataCase_ == 2) {
          return failureBuilder_.getMessage();
        }
        return Failure.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Failure failure = 2;</code>
     */
    public Builder setFailure(Failure value) {
      if (failureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        failureBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Failure failure = 2;</code>
     */
    public Builder setFailure(
        Failure.Builder builderForValue) {
      if (failureBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        failureBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Failure failure = 2;</code>
     */
    public Builder mergeFailure(Failure value) {
      if (failureBuilder_ == null) {
        if (dataCase_ == 2 &&
            data_ != Failure.getDefaultInstance()) {
          data_ = Failure.newBuilder((Failure) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 2) {
          failureBuilder_.mergeFrom(value);
        }
        failureBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Failure failure = 2;</code>
     */
    public Builder clearFailure() {
      if (failureBuilder_ == null) {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
        }
        failureBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Failure failure = 2;</code>
     */
    public Failure.Builder getFailureBuilder() {
      return getFailureFieldBuilder().getBuilder();
    }
    /**
     * <code>.astreu.core.protocol.Failure failure = 2;</code>
     */
    public FailureOrBuilder getFailureOrBuilder() {
      if ((dataCase_ == 2) && (failureBuilder_ != null)) {
        return failureBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 2) {
          return (Failure) data_;
        }
        return Failure.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Failure failure = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Failure, Failure.Builder, FailureOrBuilder>
        getFailureFieldBuilder() {
      if (failureBuilder_ == null) {
        if (!(dataCase_ == 2)) {
          data_ = Failure.getDefaultInstance();
        }
        failureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Failure, Failure.Builder, FailureOrBuilder>(
                (Failure) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 2;
      onChanged();;
      return failureBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        Connect, Connect.Builder, ConnectOrBuilder> connectBuilder_;
    /**
     * <code>.astreu.core.protocol.Connect connect = 3;</code>
     * @return Whether the connect field is set.
     */
    public boolean hasConnect() {
      return dataCase_ == 3;
    }
    /**
     * <code>.astreu.core.protocol.Connect connect = 3;</code>
     * @return The connect.
     */
    public Connect getConnect() {
      if (connectBuilder_ == null) {
        if (dataCase_ == 3) {
          return (Connect) data_;
        }
        return Connect.getDefaultInstance();
      } else {
        if (dataCase_ == 3) {
          return connectBuilder_.getMessage();
        }
        return Connect.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Connect connect = 3;</code>
     */
    public Builder setConnect(Connect value) {
      if (connectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        connectBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Connect connect = 3;</code>
     */
    public Builder setConnect(
        Connect.Builder builderForValue) {
      if (connectBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        connectBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Connect connect = 3;</code>
     */
    public Builder mergeConnect(Connect value) {
      if (connectBuilder_ == null) {
        if (dataCase_ == 3 &&
            data_ != Connect.getDefaultInstance()) {
          data_ = Connect.newBuilder((Connect) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 3) {
          connectBuilder_.mergeFrom(value);
        }
        connectBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Connect connect = 3;</code>
     */
    public Builder clearConnect() {
      if (connectBuilder_ == null) {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
        }
        connectBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Connect connect = 3;</code>
     */
    public Connect.Builder getConnectBuilder() {
      return getConnectFieldBuilder().getBuilder();
    }
    /**
     * <code>.astreu.core.protocol.Connect connect = 3;</code>
     */
    public ConnectOrBuilder getConnectOrBuilder() {
      if ((dataCase_ == 3) && (connectBuilder_ != null)) {
        return connectBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 3) {
          return (Connect) data_;
        }
        return Connect.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Connect connect = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Connect, Connect.Builder, ConnectOrBuilder>
        getConnectFieldBuilder() {
      if (connectBuilder_ == null) {
        if (!(dataCase_ == 3)) {
          data_ = Connect.getDefaultInstance();
        }
        connectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Connect, Connect.Builder, ConnectOrBuilder>(
                (Connect) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 3;
      onChanged();;
      return connectBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        Disconnect, Disconnect.Builder, DisconnectOrBuilder> disconnectBuilder_;
    /**
     * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
     * @return Whether the disconnect field is set.
     */
    public boolean hasDisconnect() {
      return dataCase_ == 4;
    }
    /**
     * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
     * @return The disconnect.
     */
    public Disconnect getDisconnect() {
      if (disconnectBuilder_ == null) {
        if (dataCase_ == 4) {
          return (Disconnect) data_;
        }
        return Disconnect.getDefaultInstance();
      } else {
        if (dataCase_ == 4) {
          return disconnectBuilder_.getMessage();
        }
        return Disconnect.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
     */
    public Builder setDisconnect(Disconnect value) {
      if (disconnectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        disconnectBuilder_.setMessage(value);
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
     */
    public Builder setDisconnect(
        Disconnect.Builder builderForValue) {
      if (disconnectBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        disconnectBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
     */
    public Builder mergeDisconnect(Disconnect value) {
      if (disconnectBuilder_ == null) {
        if (dataCase_ == 4 &&
            data_ != Disconnect.getDefaultInstance()) {
          data_ = Disconnect.newBuilder((Disconnect) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 4) {
          disconnectBuilder_.mergeFrom(value);
        }
        disconnectBuilder_.setMessage(value);
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
     */
    public Builder clearDisconnect() {
      if (disconnectBuilder_ == null) {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
        }
        disconnectBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
     */
    public Disconnect.Builder getDisconnectBuilder() {
      return getDisconnectFieldBuilder().getBuilder();
    }
    /**
     * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
     */
    public DisconnectOrBuilder getDisconnectOrBuilder() {
      if ((dataCase_ == 4) && (disconnectBuilder_ != null)) {
        return disconnectBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 4) {
          return (Disconnect) data_;
        }
        return Disconnect.getDefaultInstance();
      }
    }
    /**
     * <code>.astreu.core.protocol.Disconnect disconnect = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Disconnect, Disconnect.Builder, DisconnectOrBuilder>
        getDisconnectFieldBuilder() {
      if (disconnectBuilder_ == null) {
        if (!(dataCase_ == 4)) {
          data_ = Disconnect.getDefaultInstance();
        }
        disconnectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Disconnect, Disconnect.Builder, DisconnectOrBuilder>(
                (Disconnect) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 4;
      onChanged();;
      return disconnectBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:astreu.core.protocol.System)
  }

  // @@protoc_insertion_point(class_scope:astreu.core.protocol.System)
  private static final System DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new System();
  }

  public static System getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<System>
      PARSER = new com.google.protobuf.AbstractParser<System>() {
    @Override
    public System parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new System(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<System> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<System> getParserForType() {
    return PARSER;
  }

  @Override
  public System getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

